### ISSUE TITLE
Values in AC loads are Wrong if inverter is not installed on Phase L1

### ISSUE THREAD

**Issue by DietmarHoch** [fabian-lauer/dbus-solax-x1-pvinverter#3]
Hi,

could you please add a config Value in the Settings if the Inverter is not on Phase L1?
My inverter is installed on L3, so the Values in the Display for AC-Loads are wrong.
Please also have a look in the Discussion, because i found a solution for realtime data from the inverter

Thanks
Dietmar

**Comment by fabian-lauer** [comment]
Hi,

thanks for sharing this idea - added it to the config value and pushed to main-branch.
For me it is working - because I run on phase 1 - please give it a try.

Looking for feedback

**Comment by DietmarHoch** [comment]
Hi,

the solution is working. Great Job.
Closed

**Comment by DietmarHoch** [comment]
Hi,

the solution is working. Great Job.
Closed

**Comment by DietmarHoch** [comment]
Hi, sorry that i have to open this issue again,
it seems to me, that the values from L1 must be send, even if Zero,
with L3 (L2 maybe also) the Values are in the venus.local screen semms OK,
but not in the VRM portal. 
The Inverter is not in the Device List, or marked as not online, depends on the last OK Status.
Maybe you can check this or call me, then i can describe this better (in german).
I olso changed your code local on my device to see, if the local connection to solax wifi stick will work, yes, but...it will need mor changes.

**Comment by fabian-lauer** [comment]
Puhh....it is possible that L1 is needed - I got a bit from the official documentation (Victron) that L1 is best, also for VRM portal - can't find the link at this moment, but they mentioned a bug or display problem in VRM :-/

Yeah with the the direct values from Solax-Stick: I will not implement it on my own - I know that cloud connection has some downsides, but anyway.

Of course we can have a small phone call...

**Comment by codeworkx** [comment]
Hello together.

Are you using the driver together with "zero-feed-in / nulleinspeisung"? Did you ever test this case?

I've created a driver (https://github.com/codeworkx/dbus-serialinverter) based on yours and serialbattery from louisvdw, then connected my solis inverter (connected on ac out) via rs485 connection and modbus rtu to my cerbo. 

When doing it this way the ESS seems to be getting confused and is never able to reach zero-feed-in state. 
Looks like it tries to put all available solar energy into the battery and fully ignoring grid consumption.

When i'm injecting my pv inverter data using NodeRED to emulate EM24 as energymeter for pvinverter then this problems doesn't happen.

Settings are same in both cases. L1 and Position = 1 (AC Out)

**Comment by fabian-lauer** [comment]
Hi @codeworkx,

no idea on that at the moment - can you maybe compare with dbus-spy on SSH the values set while running in the different modes?!
Would assume that some information is missing etc.

Thx
