### ISSUE TITLE
Over the limit of API access

### ISSUE THREAD

**Issue by hoschult** [fabian-lauer/dbus-solax-x1-pvinverter#4]
Hi,

since newest VenusOS update (I guess) I'm getting from time to time the following critical error message while asking solar cloud for production:

`2022-11-08 07:21:59,518 root CRITICAL Error at _update
Traceback (most recent call last):
  File "/data/dbus-solax-x1-pvinverter/dbus-solax-x1-pvinverter.py", line 214, in _update
    meter_data = self._getSolaxCloudData()
  File "/data/dbus-solax-x1-pvinverter/dbus-solax-x1-pvinverter.py", line 151, in _getSolaxCloudData
    raise ValueError("Response (%s) is not ok - 'success'=%s 'exception'=%s" % ( URL, data['success'], data['exception']))
ValueError: Response (https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=xxxxx&sn=xxxx) is not ok - 'success'=False 'exception'=One minute access over limit!
`

Is there something wrong with my configuration? Is the query period / amount configurable?

Holger

**Comment by fabian-lauer** [comment]
Hi @hoschult  looks like the query period as you already mentioned - I think there is no need to worry - currently there is no option to configure this, but you can change directly in the script.
Search for this line
`if self._lastCloudCheck == 0 or (time.time()-self._lastCloudCheck) >= 15:`

Change the 15 to your value of choice
